//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Data.Interfaces;

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;

    public partial class Movie : IEntityBase 
    {
        public Movie()
        {
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int GenreId { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Producer { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string TrailerUri { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
