//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Data.Interfaces;

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;

    public partial class Stock : IEntityBase 
    {
        public Stock()
        {
            this.Rental = new HashSet<Rental>();
        }
    
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int UniqueKey { get; set; }
        public Nullable<bool> isAvailable { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
    }
}
